#include "nginx_sync.h"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <sys/stat.h>

#define NGINX_CONF_PATH "/etc/nginx/conf.d/autoban_rates.conf"

void nginx_sync_generate_config(AppConfig *config) {
    if (config->site_count == 0) return;

    // Chỉ thực hiện nếu thư mục tồn tại (thường là trên server thật hoặc docker)
    struct stat st;
    if (stat("/etc/nginx/conf.d", &st) != 0) {
        // Nếu không có thư mục nginx, có thể đang build/test môi trường khác, ghi ra tmp
        printf("[AutoBan] Nginx folder not found, skipping generation.\n");
        return;
    }

    FILE *f = fopen(NGINX_CONF_PATH, "w");
    if (!f) {
        perror("[AutoBan] ERROR: Cannot write Nginx sync config");
        return;
    }

    fprintf(f, "# Auto-generated by AutoBan. DO NOT EDIT MANUALLY.\n");
    fprintf(f, "# This file defines rate limits based on autoban.conf\n\n");

    for (int i = 0; i < config->site_count; i++) {
        SiteConfig *site = &config->sites[i];
        if (strlen(site->nginx_rate) > 0) {
            // Thay đổi dấu chấm thành gạch dưới cho tên zone
            char zone_name[256];
            strncpy(zone_name, site->server_name, sizeof(zone_name)-1);
            zone_name[sizeof(zone_name)-1] = '\0';
            for(char *p = zone_name; *p; p++) if(*p == '.') *p = '_';

            fprintf(f, "limit_req_zone $binary_remote_addr zone=limit_%s:10m rate=%s;\n", 
                    zone_name, site->nginx_rate);
        }
    }

    fclose(f);
    printf("[AutoBan] Synced Nginx rates to %s\n", NGINX_CONF_PATH);
}
